openapi: 3.0.3
info:
  title: ChillStream Content Service API
  version: 1.0.0
  description: REST API per la gestione di attori, film e recensioni.

servers:
  - url: http://localhost:8080

paths:
  /actors:
    get:
      summary: Recupera tutti gli attori
      responses:
        200:
          description: Lista di attori
    post:
      summary: Aggiunge più attori
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ActorInput'
      responses:
        201:
          description: Attori aggiunti

  /actors/{actor_id}:
    get:
      summary: Ottiene un attore tramite ID
      parameters:
        - $ref: '#/components/parameters/actor_id'
      responses:
        200:
          description: Dettaglio attore
        404:
          description: Attore non trovato
    put:
      summary: Aggiorna un attore
      parameters:
        - $ref: '#/components/parameters/actor_id'
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Attore aggiornato
    delete:
      summary: Elimina un attore
      parameters:
        - $ref: '#/components/parameters/actor_id'
      responses:
        204:
          description: Attore eliminato

  /actors/{actor_id}/films:
    get:
      summary: Ottiene i film associati a un attore
      parameters:
        - $ref: '#/components/parameters/actor_id'
      responses:
        200:
          description: Lista di film

  /films:
    get:
      summary: Recupera tutti i film
      responses:
        200:
          description: Lista di film
    post:
      summary: Aggiunge più film
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FilmInput'
      responses:
        201:
          description: Film aggiunti

  /films/{film_id}:
    get:
      summary: Ottiene un film tramite ID
      parameters:
        - $ref: '#/components/parameters/film_id'
      responses:
        200:
          description: Dettaglio film
    put:
      summary: Aggiorna un film
      parameters:
        - $ref: '#/components/parameters/film_id'
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Film aggiornato
    delete:
      summary: Elimina un film
      parameters:
        - $ref: '#/components/parameters/film_id'
      responses:
        204:
          description: Film eliminato

  /films/{film_id}/reviews:
    get:
      summary: Ottiene tutte le recensioni di un film
      parameters:
        - $ref: '#/components/parameters/film_id'
      responses:
        200:
          description: Lista di recensioni
    post:
      summary: Aggiunge una recensione a un film
      parameters:
        - $ref: '#/components/parameters/film_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewInput'
      responses:
        201:
          description: Recensione aggiunta

  /films/{film_id}/reviews/{review_id}:
    get:
      summary: Ottiene una recensione specifica
      parameters:
        - $ref: '#/components/parameters/film_id'
        - $ref: '#/components/parameters/review_id'
      responses:
        200:
          description: Dettaglio recensione
    put:
      summary: Aggiorna una recensione
      parameters:
        - $ref: '#/components/parameters/film_id'
        - $ref: '#/components/parameters/review_id'
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Recensione aggiornata
    delete:
      summary: Elimina una recensione
      parameters:
        - $ref: '#/components/parameters/film_id'
        - $ref: '#/components/parameters/review_id'
      responses:
        204:
          description: Recensione eliminata

components:
  parameters:
    actor_id:
      name: actor_id
      in: path
      required: true
      schema:
        type: string
    film_id:
      name: film_id
      in: path
      required: true
      schema:
        type: string
    review_id:
      name: review_id
      in: path
      required: true
      schema:
        type: string

  schemas:
    ActorInput:
      type: object
      required:
        - name
        - surname
        - date_of_birth
      properties:
        name:
          type: string
        surname:
          type: string
        date_of_birth:
          type: string

    FilmInput:
      type: object
      required:
        - title
        - actors
        - release_year
        - genre
        - rating
        - description
        - image_path
        - trailer_path
      properties:
        title:
          type: string
        actors:
          type: array
          items:
            type: string
        release_year:
          type: string
        genre:
          type: string
        rating:
          type: string
        description:
          type: string
        image_path:
          type: string
        trailer_path:
          type: string

    ReviewInput:
      type: object
      required:
        - profile_id
        - nickname
        - text
      properties:
        profile_id:
          type: string
        nickname:
          type: string
        text:
          type: string
